
image: mkovac/stretch-builder

test:
  script:
    - env|sort
    - SRCDIR=$(pwd)
    - cp -r $SRCDIR /opt/rrconf
    - apt update
    - apt install -y --no-install-recommends openssh-client ca-certificates
    - echo "CAUSEGITBASE=http://gitlab.telnet.sk/rrconf/" > /etc/default/rrconf
    - export CAUSEDEBUG=1
    - cd / && /opt/rrconf/require -x info
