
image: mkovac/stretch

test:
  script:
    - XX=$(PWD)
    - echo $XX
    - exit 0
    - apt update
    - apt install -y ssh
    - cat /proc/mounts
    - mv /builds/cause/cause /opt/cause
    - cd / && /opt/cause/require info
