
image: mkovac/stretch-builder

test:
  script:
    - env|sort
    - SRCDIR=$(pwd)
    - cp -r $SRCDIR /opt/rrconf
    - mkdir -p /etc/rrconf/repos.d
    - echo "ssh://gitlab.telnet.sk/rrconf/tutorial-" > /etc/rrconf/repos.d/33-gitlab
    - export RRDEBUG=1
    - cd / && /opt/rrconf/require -x -v -v info
