
image: mkovac/stretch-runner

test:
  script:
    - env|sort
    - SRCDIR=$(pwd)
    - cp -r $SRCDIR /opt/cause
    - apt update
    - apt install -y --no-install-recommends openssh-client ca-certificates
    - echo "CAUSEGITBASE=http://gitlab.telnet.sk/cause/" > /etc/default/cause
    - cd / && /opt/cause/require info
