
image: mkovac/stretch

test:
  script:
    - env|sort
    - SRCDIR=$(pwd)
    - mv $srcdir /opt/cause
    - apt update
    - apt install -y ssh
    - echo "CAUSEGITBASE=http://gitlab.telnet.sk/cause" > /etc/default/cause
    - cd / && /opt/cause/require info
